language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=Django==1.4.2
    - DJANGO_VERSION=https://www.djangoproject.com/download/1.5b1/tarball/
install: pip install $DJANGO_VERSION markdown docutils --use-mirrors
script: django-admin.py test --settings=markupfield.tests.settings --pythonpath=.
notifications:
    email:
        - james.p.turk@gmail.com
