language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.3
    - DJANGO_VERSION=1.4
install: pip install Django==$DJANGO_VERSION markdown docutils --use-mirrors
script: django-admin.py test --settings=markupfield.tests.settings --pythonpath=.
notifications:
    email:
        - james.p.turk@gmail.com
